

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RegistroPersonas
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class UsuariosCodesEntities : DbContext
{
    public UsuariosCodesEntities()
        : base("name=UsuariosCodesEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Persona> Personas { get; set; }

    public virtual DbSet<TipoDocumento> TiposDocumento { get; set; }

}

}

