
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RegistroPersonas
{

using System;
    using System.Collections.Generic;
    
public partial class Persona
{

    public string username { get; set; }

    public string lastname { get; set; }

    public string email { get; set; }

    public int age { get; set; }

    public int id_tipo_doc { get; set; }

    public int nro_doc { get; set; }

    public string gender { get; set; }

    public int id { get; set; }



    public virtual TipoDocumento TipoDocumento { get; set; }

}

}
